services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - "./pg_data:/postgresql/data"
    environment:
      PGDATA: /postgresql/data
      POSTGRES_PASSWORD: postgres
  pg-admin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin

