server:
  port: 5555
spring:
  jpa:
    hibernate:
      ddl-auto: update

telegramBots:
  username: kufar_notify_bot
  token: ${BOT_TOKEN}
  webhookPath: ${WEBHOOK_PATH}
  registerWebhook: true
  updateIntervalMinutes: 3
