server:
  port: 5555
spring:
  datasource:
    url: jdbc:${DATABASE_URL}/kufar-bot
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop

telegramBots:
  username: kufar_notify_bot
  token: ${BOT_TOKE}
  webhookPath: https://0bd1-46-56-202-79.eu.ngrok.io
  registerWebhook: true
  updateIntervalMinutes: 1
