server:
  port: 5555
spring:
  datasource:
    url: jdbc:${DATABASE_URL}/kufar-bot
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop

telegramBots:
  username: kufar_notify_bot
  token: ${BOT_TOKEN}
  webhookPath: https://f1bd-46-56-187-137.eu.ngrok.io
  registerWebhook: true
  updateIntervalMinutes: 1
